const hotels = [
    {
      name: 'Sample Hotel',
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?cs=srgb&dl=pexels-pixabay-164595.jpg&fm=jpg',
      address: '123 Main Street',
      postcode: '12345',
      city: 'Sample City',
      country: 'Sample Country',
      description: 'A wonderful place to stay with excellent amenities.',
      rating: 4.5,
      numReviews: 100,
      numRooms: 50,
      price: 150.0,
    },
    {
      name: 'Luxury Suites',
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?cs=srgb&dl=pexels-pixabay-164595.jpg&fm=jpg',
      address: '456 Riverside Avenue',
      postcode: '54321',
      city: 'Metropolis',
      country: 'Superland',
      description: 'Experience ultimate luxury and comfort in our suites.',
      rating: 4.8,
      numReviews: 250,
      numRooms: 100,
      price: 300.0,
    },
    {
      name: 'Seaside Resort',
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?cs=srgb&dl=pexels-pixabay-164595.jpg&fm=jpg',
      address: '789 Ocean View Drive',
      postcode: '98765',
      city: 'Beachville',
      country: 'Coastaland',
      description: 'Relax and unwind at our beachfront resort.',
      rating: 4.2,
      numReviews: 180,
      numRooms: 75,
      price: 220.0,
    },
    {
      name: 'Mountain Lodge',
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?cs=srgb&dl=pexels-pixabay-164595.jpg&fm=jpg',
      address: '101 Pines Trail',
      postcode: '54321',
      city: 'Alpineville',
      country: 'Highlands',
      description: 'Escape to the serene beauty of the mountains.',
      rating: 4.5,
      numReviews: 120,
      numRooms: 50,
      price: 180.0,
    },
    {
      name: 'City Central Hotel',
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?cs=srgb&dl=pexels-pixabay-164595.jpg&fm=jpg',
      address: '123 Downtown Street',
      postcode: '12345',
      city: 'Metropolis',
      country: 'Downtownia',
      description: 'Stay in the heart of the bustling city center.',
      rating: 4.0,
      numReviews: 300,
      numRooms: 120,
      price: 250.0,
    },
    {
      name: 'Riverside Lodge',
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?cs=srgb&dl=pexels-pixabay-164595.jpg&fm=jpg',
      address: '789 River Road',
      postcode: '98765',
      city: 'Rivertown',
      country: 'Waterside',
      description: 'Enjoy nature by the riverside at our lodge.',
      rating: 4.3,
      numReviews: 150,
      numRooms: 65,
      price: 210.0,
    },
    {
      name: 'Historic Inn',
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?cs=srgb&dl=pexels-pixabay-164595.jpg&fm=jpg',
      address: '456 Heritage Lane',
      postcode: '54321',
      city: 'Historyville',
      country: 'Antiqueland',
      description: 'Experience the charm of our historic inn.',
      rating: 4.7,
      numReviews: 190,
      numRooms: 80,
      price: 270.0,
    },
    {
      name: 'Ski Resort Lodge',
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?cs=srgb&dl=pexels-pixabay-164595.jpg&fm=jpg',
      address: '101 Snowy Slopes',
      postcode: '12345',
      city: 'Snowtown',
      country: 'Winterland',
      description: 'Hit the slopes and stay in comfort at our lodge.',
      rating: 4.6,
      numReviews: 140,
      numRooms: 55,
      price: 230.0,
    },
    {
      name: 'Cozy Cottages',
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?cs=srgb&dl=pexels-pixabay-164595.jpg&fm=jpg',
      address: '789 Meadow Lane',
      postcode: '98765',
      city: 'Natureville',
      country: 'Greenland',
      description: 'Escape to our cozy cottages in the countryside.',
      rating: 4.4,
      numReviews: 160,
      numRooms: 70,
      price: 190.0,
    },
    {
      name: 'Desert Oasis Resort',
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?cs=srgb&dl=pexels-pixabay-164595.jpg&fm=jpg',
      address: '123 Dunes Road',
      postcode: '54321',
      city: 'Sandville',
      country: 'Desertland',
      description: 'Discover luxury in the middle of the desert.',
      rating: 4.9,
      numReviews: 220,
      numRooms: 90,
      price: 320.0,
    },
  ];
  export default hotels;
  